version: '3.8'

services:
  tomcat:
    image: tomcat:8.5.56-jdk8
    container_name: my_tomcat
    restart: always
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - ./target/xxxxx.war:/usr/local/tomcat/webapps/xxx.war
      - ./logs:/usr/local/tomcat/logs
#      - ./tomcat_conf:/usr/local/tomcat/conf
    environment:
      - CATALINA_OPTS=-Xms512m -Xmx1024m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
    platform: linux/amd64  # 适配 macOS arm64
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
